import Nav from "@/components/Nav";
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={cn(
          "container relative min-h-screen  font-sans antialiased",
          inter.variable,
        )}
      >
        <Nav />
        <Separator className="mt-8" />
        {children}
      </body>
    </html>
  );
}
